### POST
http://localhost:3000/faker/cat


### gET
GET http://localhost:3000/cart/3

###
POST http://localhost:3000/cart/
Content-Type: application/json

{
  "userId": "3",
  "quantity": "5",
  "product_id": "600"
}

###
POST http://localhost:3000/faker/generate-brands

### POST Generate Products Route ###
POST http://161.156.81.77:4000/faker/generate-brands


### Sign Up
POST http://localhost:3000/users/signup
Content-Type: application/json

{
  "username": "marwan22226",
  "email": "marwan1@test.com",
  "password": "123123"
}

### Sign In
POST http://localhost:3000/users/signin
Content-Type: application/json

{
  "email": "marwan1@test.com",
  "password": "123123"
}

### Sign Out
PUT http://localhost:3000/users/signout
Authorization: 08ccb5b7-9ba8-4f0d-83c4-1f31e89808c9

### Change Password
PUT http://localhost:3000/users/changePassword
Authorization: 4cf38c4f-d678-40ca-b395-18fb6de35e80
Content-Type: application/json

{
  "currentPassword": "123123",
  "newPassword": "1212124"
}